language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libgtk-3-dev
    - libjpeg-turbo8-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install libjpeg-turbo; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
