os: Visual Studio 2015

before_build:
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "Visual Studio 14 2015 Win64" ..
  - if "%PLATFORM%"=="Win32" cmake -G "Visual Studio 14 2015" ..

build:
  project: build\ALL_BUILD.vcxproj

after_build:
- ps: |
    mkdir deploy
    if ($env:CONFIGURATION -eq "Release")
    {
      if ($env:PLATFORM -eq "Win32") 
      {
        move $env:CONFIGURATION\openpnp-capture.dll deploy\openpnp-capture_32.dll
        move win\tests\$env:CONFIGURATION\openpnp-capture-test.exe deploy\openpnp-capture-test32.exe
      }
      if ($env:PLATFORM -eq "x64") 
      {
        move $env:CONFIGURATION\openpnp-capture.dll deploy\openpnp-capture_64.dll
        move win\tests\$env:CONFIGURATION\openpnp-capture-test.exe deploy\openpnp-capture-test64.exe
      }
    }
    ls deploy

platform:
  - Win32
  - x64

configuration:
# Temporarily remove Debug to speed up builds while testing. Not really sure if there is any
# reason to build Debug anyway aside from having access to the artifacts.
#  - Debug
  - Release

artifacts:
- path: 'build/deploy'
  
deploy:
  description: 'Auto generated release.'
  provider: GitHub
  auth_token:
    secure: Lw1sX9C9TI7Xb9xXIHPn1hnp6CPHQAwr2ZOIF4QHDUWV8VOsZz+LkjAHlz2lMaSa
  artifact: 
  on:
    appveyor_repo_tag: false
    configuration: Release



    - path: build\win\tests\$(CONFIGURATION)\openpnp-capture-test.exe
  name: openpnp-capture-test.exe
- path: build\$(CONFIGURATION)\openpnp-capture.dll
  name: openpnp-capture.dll
