os: Visual Studio 2015

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: build\ALL_BUILD.vcxproj

configuration:
  - Debug
  - Release

artifacts:
- path: build\win\tests\$(CONFIGURATION)\openpnp-capture-test.exe
  name: openpnp-capture-test.exe
- path: build\$(CONFIGURATION)\openpnp-capture.dll
  name: openpnp-capture.dll
  