os: Visual Studio 2015

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: build\ALL_BUILD.vcxproj

artifacts:
- path: build\win\tests\Debug\openpnp-capture-test.exe
  name: openpnp-capture-test.exe
- path: build\Debug\openpnp-capture.dll
  name: openpnp-capture.dll